[terminal]

vt = 1

[default_session]

command = "tuigreet --time --asterisks --remember --sessions /usr/share/wayland-sessions:/usr/share/xsessions --remember-session --cmd 'niri-session'"

user = "greetd"
